---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.4
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[kibana5-test]
      - recipe[kibana5-test::wait_kibana_start]

  - name: nginx
    run_list:
      - recipe[kibana5-test]
      - recipe[kibana5-test::nginx]
      - recipe[kibana5-test::wait_kibana_start]
